#!/bin/sh

printf '[+] Requirement Installation \n'

apt-get install php python ruby

printf 'Setting Permission'
chmod +x php ssh payload Handler \
	  persistence.sh check.py

printf 'Do you have Metasploit Installed?'
read -p '[y/n] >> ' ans
if [ $ans = n ]
then
	echo "Do you want to install Metasploit?"
	read -p '>>' ques
	if [ $ques = y ]
	then
		apt-get install unstable-repo
		apt-get install metasploit
	fi
fi

exit 0






