#!/bin/sh

python check.py

echo [+] Do you want to continue?
read -p '>> ' ans

if [ $ans = yes ]
then 
	echo ‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡
	echo '[+] Successful, now your files are globally available :)'
	ssh -o "ExitOnForwardFailure yes" -R 80:localhost:4545 ssh.localhost.run
fi

exit 0
